name: device_package
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  android_id: ^0.4.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.3
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  gal: ^2.3.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  get_it: ^8.0.3
  image: ^4.5.3
  image_picker: ^1.1.2
  injectable: ^2.5.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  screen_brightness: ^2.1.2
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
